QT += core

INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

SOURCES += \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/FunctionNodes/lognode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/binaryoperationnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/divisionnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/minusnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/multynode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/plusnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/powernode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/ExpLeafes/numberleaf.cpp \
    $$PWD/Core/ExpTree/ExpNodes/ExpLeafes/variableleaf.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/absnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/cosnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/ctgnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/exponentnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/lnnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/sinnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/sqrtnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/tgnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/unaryminusnode.cpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/unaryoperationnode.cpp \
    $$PWD/Core/ExpTree/values.cpp \
    $$PWD/Core/Predicates/CharPredicates/commapr.cpp \
    $$PWD/Core/Predicates/CharPredicates/digitpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/disjunctioncharpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/dotpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/lbracketpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/letterpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/operatorpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/rbracketpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/semicolonpr.cpp \
    $$PWD/Core/Predicates/CharPredicates/underscorepr.cpp \
    $$PWD/Core/Predicates/TokenPredicates/binaryoptokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/compareprioritytokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/disjunctiontokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/emptytokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/funcseparatortokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/functionnametokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/lbrackettokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/numbertokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/rbrackettokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/unaryoptokenpredicate.cpp \
    $$PWD/Core/Predicates/TokenPredicates/variabletokenpredicate.cpp \
    $$PWD/Core/TokenFactories/funcseparatorfactory.cpp \
    $$PWD/Core/TokenFactories/identifierfactory.cpp \
    $$PWD/Core/TokenFactories/lbracketfactory.cpp \
    $$PWD/Core/TokenFactories/numberfactory.cpp \
    $$PWD/Core/TokenFactories/operatorfactory.cpp \
    $$PWD/Core/TokenFactories/rbracketfactory.cpp \
    $$PWD/Core/Tokens/binaryoptoken.cpp \
    $$PWD/Core/Tokens/funcseparatortoken.cpp \
    $$PWD/Core/Tokens/functionnametoken.cpp \
    $$PWD/Core/Tokens/lbrackettoken.cpp \
    $$PWD/Core/Tokens/numbertoken.cpp \
    $$PWD/Core/Tokens/rbrackettoken.cpp \
    $$PWD/Core/Tokens/token.cpp \
    $$PWD/Core/Tokens/unaryoptoken.cpp \
    $$PWD/Core/Tokens/variabletoken.cpp \
    $$PWD/Core/emptytokenvisitor.cpp \
    $$PWD/Core/tables.cpp \
    $$PWD/Utility/utils.cpp \
    $$PWD/Utility/position.cpp \
    $$PWD/Utility/vector.cpp \
    $$PWD/function.cpp \
    $$PWD/Core/Handlers/tokenizer.cpp \
    $$PWD/Core/Handlers/grammarscanner.cpp \
    $$PWD/Core/Handlers/rpnconverter.cpp \
    $$PWD/Core/Handlers/astcreator.cpp \
    $$PWD/parser.cpp

HEADERS += \ 
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/FunctionNodes/lognode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/binaryoperationnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/divisionnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/minusnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/multynode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/plusnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/BinaryOperationsNodes/powernode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/ExpLeafes/numberleaf.hpp \
    $$PWD/Core/ExpTree/ExpNodes/ExpLeafes/variableleaf.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/absnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/cosnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/ctgnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/exponentnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/lnnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/sinnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/sqrtnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/FunctionNodes/tgnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/unaryminusnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/UnaryOperationsNodes/unaryoperationnode.hpp \
    $$PWD/Core/ExpTree/ExpNodes/expnode.hpp \
    $$PWD/Core/ExpTree/values.hpp \
    $$PWD/Core/Predicates/CharPredicates/charpredicate.hpp \
    $$PWD/Core/Predicates/CharPredicates/commapr.hpp \
    $$PWD/Core/Predicates/CharPredicates/digitpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/disjunctioncharpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/dotpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/lbracketpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/letterpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/operatorpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/rbracketpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/semicolonpr.hpp \
    $$PWD/Core/Predicates/CharPredicates/underscorepr.hpp \
    $$PWD/Core/Predicates/TokenPredicates/binaryoptokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/compareprioritytokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/disjunctiontokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/emptytokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/funcseparatortokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/functionnametokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/lbrackettokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/numbertokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/rbrackettokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/tokencomparepredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/tokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/unaryoptokenpredicate.hpp \
    $$PWD/Core/Predicates/TokenPredicates/variabletokenpredicate.hpp \
    $$PWD/Core/TokenFactories/funcseparatorfactory.hpp \
    $$PWD/Core/TokenFactories/identifierfactory.hpp \
    $$PWD/Core/TokenFactories/lbracketfactory.hpp \
    $$PWD/Core/TokenFactories/numberfactory.hpp \
    $$PWD/Core/TokenFactories/operatorfactory.hpp \
    $$PWD/Core/TokenFactories/rbracketfactory.hpp \
    $$PWD/Core/TokenFactories/tokenfactory.hpp \
    $$PWD/Core/Tokens/binaryoptoken.hpp \
    $$PWD/Core/Tokens/funcseparatortoken.hpp \
    $$PWD/Core/Tokens/functionnametoken.hpp \
    $$PWD/Core/Tokens/lbrackettoken.hpp \
    $$PWD/Core/Tokens/numbertoken.hpp \
    $$PWD/Core/Tokens/rbrackettoken.hpp \
    $$PWD/Core/Tokens/token.hpp \
    $$PWD/Core/Tokens/unaryoptoken.hpp \
    $$PWD/Core/Tokens/variabletoken.hpp \
    $$PWD/Core/emptytokenvisitor.hpp \
    $$PWD/Core/tables.hpp \
    $$PWD/Core/tokenvisitor.hpp \
    $$PWD/Utility/utils.hpp \
    $$PWD/Utility/position.hpp \
    $$PWD/Utility/vector.hpp \
    $$PWD/function.hpp \
    $$PWD/Core/Handlers/tokenizer.hpp \
    $$PWD/Core/Handlers/grammarscanner.hpp \
    $$PWD/Core/Handlers/rpnconverter.hpp \
    $$PWD/Core/Handlers/astcreator.hpp \
    $$PWD/parser.hpp
